<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="SaveInMemory_Recipe" Id="{2eb867b7-281f-4918-a943-3695dc755aeb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SaveInMemory_Recipe : DINT
VAR_INPUT
    sData : REFERENCE TO STRING(20000);
END_VAR
VAR
    fbJson : FB_JsonSaxWriter;

    i  : INT;
    ii : INT;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>