<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="DEBUG" Id="{e85febeb-2779-48cd-bb30-f6ae088279dc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM DEBUG
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[1].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[2].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[3].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[4].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[5].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[6].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[7].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[8].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[9].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[10].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[11].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[12].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[13].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[14].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[15].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[16].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[17].bNextStation;
gMoverAxis.Q_CT_Shuttle_to_BR.asStruct[18].bNextStation;


GVL.st105_aut.xOUT_AlarmST;
GVL.st110_aut.xOUT_AlarmST;
GVL.st115_aut.xOUT_AlarmST;
GVL.st120_aut.xOUT_AlarmST;
GVL.st125_aut.xOUT_AlarmST;
GVL.st130_aut.xOUT_AlarmST;
GVL.st135_aut.xOUT_AlarmST;
GVL.st140_aut.xOUT_AlarmST;
GVL.st145_aut.xOUT_AlarmST;
GVL.st150_aut.xOUT_AlarmST;
GVL.st155_aut.xOUT_AlarmST;
GVL.st160_aut.xOUT_AlarmST;
GVL.st165_aut.xOUT_AlarmST;
GVL.st180_aut.xOUT_AlarmST;
GVL.st185_aut.xOUT_AlarmST;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>